
user  root;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    client_max_body_size 10m;

    gzip  on;
    server {
        listen       80;
        server_name  goodfloat.cloud www.goodfloat.cloud;
        # 直接重定向到HTTPS，保留原请求路径
        return 301 https://$host$request_uri;
    }
    server {
        listen       443 ssl;
        server_name  goodfloat.cloud www.goodfloat.cloud;
        server_name  localhost;
	# ===== 关键：Certbot生成的SSL证书路径 =====
        ssl_certificate      /etc/letsencrypt/live/goodfloat.cloud/fullchain.pem;
        ssl_certificate_key  /etc/letsencrypt/live/goodfloat.cloud/privkey.pem;
        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html;
        }
	location /api {
		proxy_pass_header Set-Cookie;
		proxy_pass http://127.0.0.1:2048;
		proxy_set_header Host $host;
		proxy_set_header X-Read-Ip $remote_addr;
	}
	location = /algorithms.zip {
		# 强制下载时的文件名
    		add_header Content-Disposition 'attachment; filename="algorithms.zip"';

   		 # 核心技巧：内部重写到 FastDFS 的真实路径
    		# 这里使用 rewrite ... last，它会重新触发 Nginx 内部的 location 匹配
    		rewrite ^/algorithms\.zip$ /group1/M00/00/00/kjjCYGlNDCeAGmjrAAhiQaCOWpQ085.zip last;
	}

	        location /api/upload {
                proxy_pass_header Set-Cookie;
                proxy_pass http://127.0.0.1:2048;
                proxy_set_header Host $host;
                proxy_set_header X-Real_Ip $remote_addr;
        }
    	location ~/group([0-9])/M00/ {
		root /home/zhangyc/fastdfs-nginx/data/fdfs/storage/data;
    		ngx_fastdfs_module;
	}

        
	error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

    }


}
